language: java

jdk:
  - oraclejdk7

env:
  - PATH=$PATH:/tmp/sonar-runner-2.4/bin SONAR_DL=http://downloads.sonarsource.com/sonarqube/sonarqube-4.5.4.zip SONARHOME=/tmp/sonarqube-4.5.4
  - PATH=$PATH:/tmp/sonar-runner-2.4/bin SONAR_DL=http://downloads.sonarsource.com/sonarqube/sonarqube-5.0.1.zip SONARHOME=/tmp/sonarqube-5.0.1
  - PATH=$PATH:/tmp/sonar-runner-2.4/bin SONAR_DL=http://downloads.sonarsource.com/sonarqube/sonarqube-5.1.1.zip SONARHOME=/tmp/sonarqube-5.1.1

install:
  - gem install puppet-lint

script:
  - ./gradlew build integTest

before_install:
 - chmod +x gradlew
